/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package randomgamificationthing;


import java.awt.Color;
import java.awt.Image;
import java.awt.Insets;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.DEFAULT_OPTION;
import static javax.swing.JOptionPane.OK_OPTION;

/**
 *
 * @author Trevor
 */
public class GameWindow extends javax.swing.JFrame {
    
    private int selectedEvent;
    Game game;

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        selectedEvent=-1;
        initComponents();
        //game= new Game(0,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();
        eventButton1 = new javax.swing.JButton();
        eventButton2 = new javax.swing.JButton();
        eventButton3 = new javax.swing.JButton();
        eventButton4 = new javax.swing.JButton();
        eventButton5 = new javax.swing.JButton();
        gameProgressBar = new javax.swing.JProgressBar();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayArea.setColumns(20);
        displayArea.setRows(5);
        displayArea.setEditable(false);
        jScrollPane1.setViewportView(displayArea);

        ImageIcon img = createImageIcon("GameIcons/shirt.JPG","plz work");
        eventButton1.setIcon(img);
        eventButton1.setMargin(new Insets(0, 0, 0, 0));
        eventButton1.setBackground(Color.WHITE);
        eventButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventButton1ActionPerformed(evt);
            }
        });

        eventButton2.setText(null);
        ImageIcon pants = createImageIcon("GameIcons/pants.JPG","plz work");
        eventButton2.setIcon(pants);
        eventButton2.setMargin(new Insets(0, 0, 0, 0));
        eventButton2.setBackground(Color.WHITE);
        eventButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventButton2ActionPerformed(evt);
            }
        });

        ImageIcon hat = createImageIcon("GameIcons/hat.JPG","plz work");
        eventButton3.setIcon(hat);
        eventButton3.setMargin(new Insets(0, 0, 0, 0));
        eventButton3.setBackground(Color.WHITE);
        eventButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventButton3ActionPerformed(evt);
            }
        });

        ImageIcon sock = createImageIcon("GameIcons/sock.JPG","plz work");
        eventButton4.setIcon(sock);
        eventButton4.setMargin(new Insets(0, 0, 0, 0));
        eventButton4.setBackground(Color.WHITE);
        eventButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventButton4ActionPerformed(evt);
            }
        });

        ImageIcon under = createImageIcon("GameIcons/Underpanties.JPG","plz work");
        eventButton5.setIcon(under);
        eventButton5.setMargin(new Insets(0, 0, 0, 0));
        eventButton5.setBackground(Color.WHITE);
        eventButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventButton5ActionPerformed(evt);
            }
        });

        gameProgressBar.setMaximum(100);
        gameProgressBar.setMinimum(0);

        jTextField1.setEditable(false);
        jTextField1.setText("Laundry Progress:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(eventButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(eventButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(eventButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(eventButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eventButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(eventButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void eventButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventButton2ActionPerformed
        setSelectedEvent(1);
    }//GEN-LAST:event_eventButton2ActionPerformed
        
    private void eventButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventButton1ActionPerformed
        setSelectedEvent(0);
    }//GEN-LAST:event_eventButton1ActionPerformed

    private void eventButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventButton3ActionPerformed
        setSelectedEvent(2);
    }//GEN-LAST:event_eventButton3ActionPerformed

    private void eventButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventButton4ActionPerformed
        setSelectedEvent(3);
    }//GEN-LAST:event_eventButton4ActionPerformed

    private void eventButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventButton5ActionPerformed
        setSelectedEvent(4);
    }//GEN-LAST:event_eventButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void open() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
                
            }
        });
        //playGame();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea displayArea;
    private javax.swing.JButton eventButton1;
    private javax.swing.JButton eventButton2;
    private javax.swing.JButton eventButton3;
    private javax.swing.JButton eventButton4;
    private javax.swing.JButton eventButton5;
    private javax.swing.JProgressBar gameProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the selectedEvent
     */
    public int getSelectedEvent() {
        return selectedEvent;
    }

    /**
     * @param selectedEvent the selectedEvent to set
     */
    public void setSelectedEvent(int selectedEvent) {
        this.selectedEvent = selectedEvent;
    }

    /**
     * @param displayArea the displayArea to set
     */
    public void setDisplayText(String eventText) {
        displayArea.append(eventText + "\r\n");
    }
    
    public void setprogress(int progress) {
        gameProgressBar.setValue(progress);
    }
    
    public void playGame(){
        int choice = JOptionPane.showConfirmDialog(null, "Select the article of clothing that the game calls for to complete the laundry", "Laundry Game Version 1.0", JOptionPane.DEFAULT_OPTION);
        if(choice==OK_OPTION){
            game = new Game(0,0);
            setVisible(true);
            //setDisplayText("");
           // setDisplayText("Select the article of clothing that the game calls for to complete the laundry");
            setDisplayText("HERE WE GO!");
            while(game.getProgress()<100){
                int i = game.chooseEvent();
                setDisplayText(game.getEvents()[i].getText());
                checkInput(i);
                setprogress(game.getProgress());
            }
            //setDisplayText("Good Job! The laundry is all done!");
            setVisible(false);
            JOptionPane.showMessageDialog(null, "Good Job! The laundry is all done!", "CONGRATULATIONS", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }else{
            System.exit(0);
        }
    }
    
    public void checkInput(int i){
        String text ="";
        while (getSelectedEvent()==-1){
            System.out.println("YOLO");
        }
        if (getSelectedEvent()==i){
            game.incrementProgress();
            if(game.getProgress()<100){
                text="Good Job! What do we need next...?";
            }
        }else{
            text="I'm Sorry, that was wrong! The laundry will never get done at this rate!";
            game.decrementProgress();
        }
        setDisplayText(text);
        setSelectedEvent(-1);
    }
    
    protected ImageIcon createImageIcon(String path,
                                           String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("Couldn't find file: " + path);
        return null;
    }
}

}
